// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/share-card/CleanUI.tsx": () =>
    import("../components/mockups/share-card/CleanUI.tsx"),
  "./components/mockups/share-card/DeepNavy.tsx": () =>
    import("../components/mockups/share-card/DeepNavy.tsx"),
  "./components/mockups/share-card/SageGarden.tsx": () =>
    import("../components/mockups/share-card/SageGarden.tsx"),
  "./components/mockups/share-card/WarmIvory.tsx": () =>
    import("../components/mockups/share-card/WarmIvory.tsx"),
};
